### PR TITLE
Update Bahmni Vagrant box to come with oh-my-zsh shell by default to …

### PR DESCRIPTION
**Pull request by m0un10**
…make it easier for newbies to navigate inside Vagrant.

As per:
https://trello.com/c/0qrhtyJW/57-update-bahmni-vagrant-box-to-come-with-oh-my-zsh-shell-by-default-to-make-it-easier-for-newbies-to-navigate-inside-vagrant

### CODE REVIEW

**Comment by brookingcharlie** [comment]
Nice one, Craig!

**Review by binduak — DISMISSED** [review]
Hi @craigbarrau,
Thanks for the pull request.
Is there any reason to add backslash at the end of the line as its causing syntax error. Also we need to add 'sudo' as shell script to be run on Bahmni server as a root user. Please send the pull request with the changes. Thank you.

**Comment by binduak** [comment]
Hi @craigbarrau ,
Thanks for the pull request.

**Comment by m0un10** [comment]
Thanks @binduak 

I'm unable to test this end-to-end as part of the full `packer` flow due to a requirement in `template.json` to use Atlas as part of the Packer build (this requires credentials I don't have). Do you have any suggestions for testing this locally as part of the `packer` build in case of future PRs?

I have made the sudo change and fixed the trailing backslash. My bad there... I had some additional steps which I had later removed due to their redundancy apologies on skipping the retest there. Should be all good now.

Thanks!

**Comment by binduak** [comment]
Hi @craigbarrau,
Thanks for the pull request with the changes.
I have merged your pull request. I will add the steps for the `packer` build in the [Bahmni wiki](wiki.bahmni.org) soon and I will share the page with you. 
Thank you!

**Comment by binduak** [comment]
Hi @craigbarrau ,
Please check this [Bahmni Wiki](https://bahmni.atlassian.net/wiki/display/BAH/Build+Bahmni+Vagrant+Box+using+Packer) page for the instructions to build Bahmni Vagrant Box with packer.
Thanks!

**Pull request merged**
